// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6E8d1wgSPMFN0tWpbtEic8pwJn9ALK2w',
    appId: '1:922938973568:web:82a380171af06b4d05f565',
    messagingSenderId: '922938973568',
    projectId: 'loginapp-402ea',
    authDomain: 'loginapp-402ea.firebaseapp.com',
    storageBucket: 'loginapp-402ea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBocWJvildxioPyykcLxnnk9PJOKcOps10',
    appId: '1:922938973568:android:4e9c359b1ab62ff005f565',
    messagingSenderId: '922938973568',
    projectId: 'loginapp-402ea',
    storageBucket: 'loginapp-402ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuVgj7t4cFg5IoqyDBT1omD0n-Qr8C2zI',
    appId: '1:922938973568:ios:95367971f473c2bf05f565',
    messagingSenderId: '922938973568',
    projectId: 'loginapp-402ea',
    storageBucket: 'loginapp-402ea.firebasestorage.app',
    iosBundleId: 'com.example.loginapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuVgj7t4cFg5IoqyDBT1omD0n-Qr8C2zI',
    appId: '1:922938973568:ios:95367971f473c2bf05f565',
    messagingSenderId: '922938973568',
    projectId: 'loginapp-402ea',
    storageBucket: 'loginapp-402ea.firebasestorage.app',
    iosBundleId: 'com.example.loginapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6E8d1wgSPMFN0tWpbtEic8pwJn9ALK2w',
    appId: '1:922938973568:web:d5dba12dd8f82b1d05f565',
    messagingSenderId: '922938973568',
    projectId: 'loginapp-402ea',
    authDomain: 'loginapp-402ea.firebaseapp.com',
    storageBucket: 'loginapp-402ea.firebasestorage.app',
  );
}
